apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-web-app
  labels:
    app: node-web-app
spec:
  replicas: 3
  selector:
    matchLabels:
        app: node-web-app
  template:
      metadata:
        labels:
          app: node-web-app
      spec:
        containers:
          - name: node-web-app
            image: hxnyiiy01/node-web-app
            ports:
              - containerPort: 8000
