apiVersion: apps/v1
kind: Deployment
metadata:
  name: remoteapi
  labels:
    app: remoteapi
spec:
  replicas: 3
  selector:
    matchLabels:
        app: remoteapi
  template:
      metadata:
        labels:
          app: remoteapi
      spec:
        containers:
          - name: remoteapi
            image: hxnyiiy01/remoteapi
            ports:
              - containerPort: 8000
