apiVersion: v1
kind: Service
metadata:
  name: remoteapi
  labels:
    run: remoteapi
spec:
  type: NodePort  # NodePort로 수정
  ports:
    - nodePort: 30800     # 외부에서 접근할 포트
      port: 8080          # 서비스 내부 포트
      targetPort: 8000    # 실제 컨테이너 포트
      protocol: TCP
      name: http
  selector:
    app: remoteapi
